export const HOME_PAGE = "/";
export const LOVEDONES_PAGE = "/lovedones";
export const PETS_PAGE = "/pets";
export const STARTED_PAGE = "/started";
export const ALGORITHM_PAGE = "/algorithm";
export const ABOUT_PAGE = "/about";
export const BLOG_PAGE = "/blog";
export const toBlogPageId = (id: string): string => `${BLOG_PAGE}/${id}`;
export const PRIVACY_PAGE = "/privacy";
export const PRICING_PAGE = "/pricing";
export const NOT_FOUND_PAGE = "/any-link_qwertyuioasdfasdfadsc123";
export const FAQ_PAGE = "/faq";
export const REVIEWS_PAGE = "/reviews";
