export const relationshipListPerson: { value: string; label: string }[] = [
  { value: "friend", label: "Friend" },
  { value: "self", label: "Self" },
  { value: "grandMother", label: "Grandmother" },
  { value: "motherInLaw", label: "Mother-lin-law" },
  { value: "mother", label: "Mother" },
  { value: "stepMother", label: "lStep-Mother" },
  { value: "wife", label: "Wife" },
  { value: "granddaughter", label: "Granddaughter" },
  { value: "daughter", label: "Daughter" },
  { value: "sister", label: "Sister" },
  { value: "niece", label: "Niece" },
  { value: "aunt", label: "Aunt" },
  { value: "grandfather", label: "Grandfather" },
  { value: "father", label: "Father" },
  { value: "fatherInLaw", label: "Father-lin-Law" },
  { value: "stepFather", label: "lStep-Father" },
  { value: "husband", label: "Husband" },
  { value: "brother", label: "Brother" },
  { value: "grandson", label: "Grandson" },
  { value: "son", label: "Son" },
  { value: "uncle", label: "Uncle" },
  { value: "partnerSignificant", label: "Partner (lSignificant Other)" },
  { value: "cousin", label: "Cousin" },
  { value: "nephew", label: "Nephew" },
  { value: "other", label: "Other" },
];

export const relationshipListPet: { value: string; label: string }[] = [
  { value: "dog", label: "Dog" },
  { value: "cat", label: "Cat" },
  { value: "horse", label: "Horse" },
  { value: "rabbit", label: "Rabbit" },
  { value: "other", label: "Other" },
];
