import Head from "next/head";

const AppHead = () => {
  return (
    <Head>
      <link
        rel="preload"
        href="../../shared/fonts/CreattionDemo/CreattionDemo.woff2"
        as="font"
        type="font/woff"
      />
      <link
        rel="preload"
        href="../../shared/fonts/CreattionDemo/CreattionDemo.woff"
        as="font"
        type="font/woff"
      />
      <link
        rel="preload"
        href="../../shared/fonts/Helvetica/helvetica_bold.woff"
        as="font"
        type="font/woff"
      />
      <link
        rel="preload"
        href="../../shared/fonts/Helvetica/helvetica_bold.woff2"
        as="font"
        type="font/woff2"
      />
      <link
        rel="preload"
        href="../../shared/fonts/InstrumentSerif/InstrumentSerif-Regular.woff"
        as="font"
        type="font/woff"
      />
      <link
        rel="preload"
        href="../../shared/fonts/InstrumentSerif/InstrumentSerif-Regular.woff2"
        as="font"
        type="font/woff2"
      />
      <link
        rel="preload"
        href="../../shared/fonts/InstrumentSerif/InstrumentSerif-Regular.woff2"
        as="font"
        type="font/woff2"
      />
      <link
        rel="preload"
        href="../../shared/fonts/Travel/Travel-November.woff2"
        as="font"
        type="font/woff2"
      />
      <link
        rel="preload"
        href="../../shared/fonts/Travel/Travel-November.woff2"
        as="font"
        type="font/woff2"
      />
      <link
        rel="preload"
        href="../../shared/fonts/Poppins/Poppins-Bold.woff2"
        as="font"
        type="font/woff2"
      />
      <link
        rel="preload"
        href="../../shared/fonts/Poppins/Poppins-Bold.woff2"
        as="font"
        type="font/woff2"
      />
      <link
        rel="preload"
        href="../../shared/fonts/Poppins/Poppins-Light.woff2"
        as="font"
        type="font/woff2"
      />
      <link
        rel="preload"
        href="../../shared/fonts/Poppins/Poppins-Light.woff2"
        as="font"
        type="font/woff2"
      />
      <link
        rel="preload"
        href="../../shared/fonts/Poppins/Poppins-Medium.woff2"
        as="font"
        type="font/woff2"
      />
      <link
        rel="preload"
        href="../../shared/fonts/Poppins/Poppins-Medium.woff2"
        as="font"
        type="font/woff2"
      />
      <link
        rel="preload"
        href="../../shared/fonts/Poppins/Poppins-Regular.woff2"
        as="font"
        type="font/woff2"
      />
      <link
        rel="preload"
        href="../../shared/fonts/Poppins/Poppins-Regular.woff2"
        as="font"
        type="font/woff2"
      />
      <link
        rel="preload"
        href="../../shared/fonts/Poppins/Poppins-SemiBold.woff2"
        as="font"
        type="font/woff2"
      />
      <link
        rel="preload"
        href="../../shared/fonts/Poppins/Poppins-SemiBold.woff2"
        as="font"
        type="font/woff2"
      />
    </Head>
  );
};

export default AppHead;
